name: animated_list_example
version:

environment:
  sdk:

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons:

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true